version: '3.8'

services:
  database:
    container_name: customerX
    image: postgres:alpine
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - app-net

volumes:
  db-volume:

networks:
  app-net:
